In [1]:
# %load_ext rpy2.ipython
# #import rpy2.robjects as robjects
import codecs
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from tqdm import tqdm_notebook as tqdm
import time
import warnings;warnings.simplefilter('ignore')
os.listdir('D:/AI-work/南亞case/yo-jupyter/R11程式')

['#2反應槽(20200201-20200212)開車資料.csv',
 '.Rhistory',
 'PA_201605-2020001更新R11(20200801).csv',
 'R11註解.txt',
 'tag_cleaned.csv',
 'tag盤點表20200801.csv',
 'tag盤點表20200801.xlsx',
 'train_cleaned(C).csv',
 'train_cleaned(R).csv',
 'train_cleaned(R1).csv',
 'train_cleaned.csv',
 'utils.py',
 'web(R11).py',
 'yo_R11_Actor.ipynb',
 'yo_R11_API_test.ipynb',
 'yo_R11_Critic_Actor.ipynb',
 'yo_R11_ETL.ipynb',
 'yo_R11_preprocessing.ipynb',
 'yo_R11_stream_lasso.ipynb',
 '.ipynb_checkpoints',
 'modelpkl',
 'runs',
 '__pycache__',
 '壓縮檔',
 'r2.csv']

# load raw df

In [2]:
# df = pd.read_csv('../data/PA_201605-2020001更新R10(20200602).csv',
#                  index_col=0,
#                  parse_dates=True,
#                  encoding='latin-1')
df = pd.read_csv('C:/Users/bigje/Desktop/AI中心/yo-jupyter/R11程式/PA_201605-2020001更新R11(20200801).csv',
                 index_col=0,
                 parse_dates=True,
                 encoding='latin-1')
df = df.iloc[:-1,:]
print(df.shape)
df.head()

(193823, 98)

,MLPAP_TI-0706B02,MLPAP_TI-0706B03,MLPAP_TI-0706B04,MLPAP_TI-0706B05,MLPAP_TI-0706B06,MLPAP_TI-0706B07,MLPAP_TI-0706B08,MLPAP_TI-0706B09,MLPAP_TI-0706B10,MLPAP_TI-0706B11,...,MLPAP_FI-V211.PV,MLPAP_FI-V211.PV(Âà´««á),MLPAP_PI-0658.PV,MLPAP_TIC-0757.PV,MLPAP_V225-PHD,MLPAP_PI-0771.PV,MLPAP_TRC-0747.PV,MLPAP_TJR-0881.PV,MLPAP_TI3-1110.PV,MLPAP_FQI-0997.SMH
2016-05-09 00:00:00,400,401.957,400.752,402.251,401.149,401,400.05,403,402,401,...,[-11059] No Good Data For Calculation,#VALUE!,-1,1.63519,0.009,-1.38272,133.1,156.434,26.47590256,0
2016-05-09 00:10:00,400,401.943,400.95,402.249,401,401,400.25,403,402,401,...,[-11059] No Good Data For Calculation,#VALUE!,-1,1.62501,0.009,-1.38273,133.1,156.434,26.5,0
2016-05-09 00:20:00,400,401.9,400.9,402.101,401,401,400.1,403,402,401,...,[-11059] No Good Data For Calculation,#VALUE!,-0.898558,1.64978,0.009,-1.4,133.1,156.5,26.70000076,0
2016-05-09 00:30:00,400,401.95,400.9,402.3,401,401,400.145,403,402,401,...,[-11059] No Good Data For Calculation,#VALUE!,-0.50901,1.63519,0.009,-1.4,133.2,156.434,26.62422943,0
2016-05-09 00:40:00,400,402,400.85,402.176,401,401,400.405,403,402,401,...,[-11059] No Good Data For Calculation,#VALUE!,-0.992771,1.65426,0.009,-1.3,133.1,156.434,26.39999962,0

# load test data

In [3]:
test_df = pd.read_csv('C:/Users/bigje/Desktop/AI中心/yo-jupyter/R11程式/#2反應槽(20200201-20200212)開車資料.csv',
                 index_col=0,
                 parse_dates=True,
                 encoding='latin-1')
test_df = test_df.dropna(axis=0)
print(test_df.shape)
test_df.head()

(1585, 97)

,MLPAP_TI-0706B02,MLPAP_TI-0706B03,MLPAP_TI-0706B04,MLPAP_TI-0706B05,MLPAP_TI-0706B06,MLPAP_TI-0706B07,MLPAP_TI-0706B08,MLPAP_TI-0706B09,MLPAP_TI-0706B10,MLPAP_TI-0706B11,...,MLPAP_FR-0791.PV,MLPAP_FI-V211.PV,MLPAP_FI-V211.PV(Âà´««á),MLPAP_PI-0658.PV,MLPAP_TIC-0757.PV,MLPAP_V225-PHD,MLPAP_PI-0771.PV,MLPAP_TRC-0747.PV,MLPAP_TJR-0881.PV,MLPAP_TI3-1110.PV
2020-02-01 00:00:00,377.0,384.0,383,383.0,380,380.0,379.0,377,375.0,373,...,13.45998001,5596.255859,5588.712106,336.2572021,0.400000006,0.01,44.82498169,175.000000,154.3999939,12.10000038
2020-02-01 00:10:00,377.0,384.0,383,384.0,381,381.0,380.0,377,376.0,373,...,13.47245789,5568.742676,5561.236011,342,0.474259675,0.01,52.9498291,174.899994,154.3999939,12
2020-02-01 00:20:00,377.0,384.0,383,384.0,381,381.0,380.0,377,376.0,373,...,13.55996227,5592.000000,5584.461984,342.2573853,0.374261886,0.01,53.65019226,174.925736,154.4257355,11.95688915
2020-02-01 00:30:00,377.0,384.0,383,384.0,381,381.0,380.0,377,376.0,373,...,13.5599823,5432.380371,5425.057522,343,0.5,0.01,53.79999924,174.800003,154.5,11.80000019
2020-02-01 00:40:00,377.0,384.0,383,384.0,381,381.0,380.0,377,376.0,373,...,13.84774494,5575.185547,5567.670197,342,0.674252152,0.01,52.70000076,174.800003,154.3999939,11.5

In [4]:
df['DATA OF USE']

2016-05-09 00:00:00         4.75646879756469E-06*1
2016-05-09 00:10:00         4.75646879756469E-06*2
2016-05-09 00:20:00         4.75646879756469E-06*3
2016-05-09 00:30:00         4.75646879756469E-06*4
2016-05-09 00:40:00         4.75646879756469E-06*5
                                  ...
2020-01-14 23:00:00    4.75646879756469E-06*193819
2020-01-14 23:10:00    4.75646879756469E-06*193820
2020-01-14 23:20:00    4.75646879756469E-06*193821
2020-01-14 23:30:00    4.75646879756469E-06*193822
2020-01-14 23:40:00    4.75646879756469E-06*193823
Name: DATA OF USE, Length: 193823, dtype: object

In [5]:
test_df['DATA OF USE']

2020-02-01 00:00:00    4.75646879756469E-06*1363
2020-02-01 00:10:00    4.75646879756469E-06*1364
2020-02-01 00:20:00    4.75646879756469E-06*1365
2020-02-01 00:30:00    4.75646879756469E-06*1366
2020-02-01 00:40:00    4.75646879756469E-06*1367
                                 ...
2020-02-11 23:20:00    4.75646879756469E-06*2943
2020-02-11 23:30:00    4.75646879756469E-06*2944
2020-02-11 23:40:00    4.75646879756469E-06*2945
2020-02-11 23:50:00    4.75646879756469E-06*2946
2020-02-12 00:00:00    4.75646879756469E-06*2947
Name: DATA OF USE, Length: 1585, dtype: object

# combine

In [6]:
full = df.append(test_df)
df = full

# load raw tag

In [7]:
# tag = pd.read_excel('../data/tag盤點表20200423.xlsx')
#tag = pd.read_excel('../data/tag盤點表20200602R1.xlsx')
tag = pd.read_excel('C:/Users/bigje/Desktop/AI中心/yo-jupyter/R11程式/tag盤點表20200801.xlsx')
print(tag.shape)
tag.head()

(97, 10)

,item,TAG,chinese,character,unit,category,period,min,max,推測顯著性(依製程經驗)
0,1.0,MLPAP_TJC-0627.PV,OX預熱器出口溫度,溫度,℃,可控制因子,1分鐘2筆,145,160,***
1,2.0,MLPAP_TRC-0610.PV,空氣預熱器出口溫度,溫度,℃,可控制因子,1分鐘2筆,160,200,***
2,3.0,MLPAP_FR-0632.PV,汽機風量,流量,KNM3/HR,可控制因子,1分鐘2筆,64,85.4,****
3,4.0,MLPAP_FQ-0619.PV,OX入料量,流量,kg/HR,可控制因子,1分鐘2筆,2000,8000,****
4,5.0,MLPAP_TIC-0757A.PV,反應槽鹽浴溫度,溫度,℃,可控制因子,1分鐘2筆,345,365,****

In [8]:
# 根據廠方說法 應大於64
tag.loc[tag.chinese == '汽機風量','min'] = 64

In [9]:
tag.loc[tag.chinese == '汽機風量']

,item,TAG,chinese,character,unit,category,period,min,max,推測顯著性(依製程經驗)
2,3.0,MLPAP_FR-0632.PV,汽機風量,流量,KNM3/HR,可控制因子,1分鐘2筆,64,85.4,****

In [10]:
stream_list = tag[tag.chinese.str.contains('蒸氣')==True].TAG.tolist() # 在tag中取出包含""的資料，再把前面N個欄名轉成list
stream_list

['MLPAP_FR-0755PV(轉換後)', 'MLPAP_FR-0791.PV', 'MLPAP_FI-V211.PV(轉換後)']

# clean df and tag

In [11]:
# rename
df.columns = [str(i).replace('TI','TJ') for i in df.columns]
tag.TAG = [str(i).replace('TI','TJ') for i in tag.TAG]
df.columns = [i.replace('Âà´««á','轉換後')for i in df.columns]

# drop not need columns
df = df.drop(['MLPAP_FR-0755.PV','MLPAP_FI-V211.PV'],axis=1)

# extend tag
temp = tag[tag['TAG'] == tag['TAG'][tag['TAG'].str.contains('0757A')].values[0]].copy()
temp['TAG'] = 'MLPAP_TJ-0757B.PV'
tag = tag.append(temp).reset_index(drop=True)

In [12]:
df.columns

Index(['MLPAP_TJ-0706B02', 'MLPAP_TJ-0706B03', 'MLPAP_TJ-0706B04',
       'MLPAP_TJ-0706B05', 'MLPAP_TJ-0706B06', 'MLPAP_TJ-0706B07',
       'MLPAP_TJ-0706B08', 'MLPAP_TJ-0706B09', 'MLPAP_TJ-0706B10',
       'MLPAP_TJ-0706B11', 'MLPAP_TJ-0706B12', 'MLPAP_TJ-0706B13',
       'MLPAP_TJ-0706B14', 'MLPAP_TJ-0706B15', 'MLPAP_TJ-0706B16',
       'MLPAP_TJ-0706B17', 'MLPAP_TJ-0706B18', 'MLPAP_TJ-0706B19',
       'MLPAP_TJ-0706B20', 'MLPAP_TJ-0706B21', 'MLPAP_TJ-0706B22',
       'MLPAP_TJ-0706B23', 'MLPAP_TJ-0706B24', 'MLPAP_TJ-0716A02',
       'MLPAP_TJ-0716A03', 'MLPAP_TJ-0716A04', 'MLPAP_TJ-0716A05',
       'MLPAP_TJ-0716A06', 'MLPAP_TJ-0716A07', 'MLPAP_TJ-0716A08',
       'MLPAP_TJ-0716A09', 'MLPAP_TJ-0716A10', 'MLPAP_TJ-0716A11',
       'MLPAP_TJ-0716A12', 'MLPAP_TJ-0716A13', 'MLPAP_TJ-0716A14',
       'MLPAP_TJ-0716A15', 'MLPAP_TJ-0716A16', 'MLPAP_TJ-0716A17',
       'MLPAP_TJ-0716A18', 'MLPAP_TJ-0716A19', 'MLPAP_TJ-0716A20',
       'MLPAP_TJ-0716A21', 'MLPAP_TJ-0716A22', 'MLPAP_TJ-0716A23',
       'MLPAP_TJR-0715A1.PV', 'MLPAP_TJR-0715A2.PV', 'MLPAP_TJR-0715B1.PV',
       'MLPAP_TJR-0715B2.PV', 'MLPAP_TJR-0720A1.PV', 'MLPAP_TJR-0720A2.PV',
       'MLPAP_TJR-0720B1.PV', 'MLPAP_TJR-0720B2.PV', 'MLPAP_TJR-0762A1.PV',
       'MLPAP_TJR-0762A2.PV', 'MLPAP_TJR-0762B1.PV', 'MLPAP_TJR-0762B2.PV',
       'MLPAP_TJ-0706A02', 'MLPAP_TJ-0706B01', 'MLPAP_TJ-0706C01',
       'MLPAP_TJ-0706D01', 'MLPAP_TJ-0716B01', 'MLPAP_TJ-0716C01',
       'MLPAP_TJ-0716D01', 'MLPAP_TJ-0716E01', 'MLPAP_TJ-0716A01',
       'MLPAP_TJ-0706E01', 'MLPAP_TJ-0706A01', 'MLPAP_TJ-0716D02',
       'MLPAP_TJC-0627.PV', 'MLPAP_TRC-0610.PV', 'MLPAP_FR-0632.PV',
       'MLPAP_FQ-0619.PV', 'MLPAP_TJC-0757A.PV', 'MLPAP_TJ-0757B.PV',
       'MLPAP_PIC-0741.PV', 'MLPAP_LIC-0738.PV', 'MLPAP_PIC-0761.PV',
       'MLPAP_TRC-0762.PV', 'MLPAP_LRC-0729.PV', 'MLPAP_TJC-1721.PV',
       'MLPAP_TRC-1734.PV', 'MLPAP_TJR-0721.PV', 'MLPAP_FQI-0997.PV',
       'DATA OF USE', 'MLPAP_FR-0755PV(轉換後)', 'MLPAP_FR-0791.PV',
       'MLPAP_FI-V211.PV(轉換後)', 'MLPAP_PI-0658.PV', 'MLPAP_TJC-0757.PV',
       'MLPAP_V225-PHD', 'MLPAP_PI-0771.PV', 'MLPAP_TRC-0747.PV',
       'MLPAP_TJR-0881.PV', 'MLPAP_TJ3-1110.PV', 'MLPAP_FQI-0997.SMH',
       'MLPAP_FR-0755.PV(轉換後)'],
      dtype='object')

In [13]:
tag['TAG']

0      MLPAP_TJC-0627.PV
1      MLPAP_TRC-0610.PV
2       MLPAP_FR-0632.PV
3       MLPAP_FQ-0619.PV
4     MLPAP_TJC-0757A.PV
             ...
93    MLPAP_FQI-0997.SMH
94                   nan
95                品質模型使用
96        MLPAP_V225-PHD
97     MLPAP_TJ-0757B.PV
Name: TAG, Length: 98, dtype: object

In [14]:
print('only in tag:',set(tag['TAG'])-set(df.columns))
print('only in df:',set(df.columns)-set(tag['TAG']))

only in tag: {'品質模型使用', 'MLPAP_TJ-0881.PV', 'nan'}
only in df: {'MLPAP_FR-0755.PV(轉換後)', 'MLPAP_TJR-0881.PV'}

In [15]:
set(df.columns)

{'DATA OF USE',
 'MLPAP_FI-V211.PV(轉換後)',
 'MLPAP_FQ-0619.PV',
 'MLPAP_FQI-0997.PV',
 'MLPAP_FQI-0997.SMH',
 'MLPAP_FR-0632.PV',
 'MLPAP_FR-0755.PV(轉換後)',
 'MLPAP_FR-0755PV(轉換後)',
 'MLPAP_FR-0791.PV',
 'MLPAP_LIC-0738.PV',
 'MLPAP_LRC-0729.PV',
 'MLPAP_PI-0658.PV',
 'MLPAP_PI-0771.PV',
 'MLPAP_PIC-0741.PV',
 'MLPAP_PIC-0761.PV',
 'MLPAP_TJ-0706A01',
 'MLPAP_TJ-0706A02',
 'MLPAP_TJ-0706B01',
 'MLPAP_TJ-0706B02',
 'MLPAP_TJ-0706B03',
 'MLPAP_TJ-0706B04',
 'MLPAP_TJ-0706B05',
 'MLPAP_TJ-0706B06',
 'MLPAP_TJ-0706B07',
 'MLPAP_TJ-0706B08',
 'MLPAP_TJ-0706B09',
 'MLPAP_TJ-0706B10',
 'MLPAP_TJ-0706B11',
 'MLPAP_TJ-0706B12',
 'MLPAP_TJ-0706B13',
 'MLPAP_TJ-0706B14',
 'MLPAP_TJ-0706B15',
 'MLPAP_TJ-0706B16',
 'MLPAP_TJ-0706B17',
 'MLPAP_TJ-0706B18',
 'MLPAP_TJ-0706B19',
 'MLPAP_TJ-0706B20',
 'MLPAP_TJ-0706B21',
 'MLPAP_TJ-0706B22',
 'MLPAP_TJ-0706B23',
 'MLPAP_TJ-0706B24',
 'MLPAP_TJ-0706C01',
 'MLPAP_TJ-0706D01',
 'MLPAP_TJ-0706E01',
 'MLPAP_TJ-0716A01',
 'MLPAP_TJ-0716A02',
 'MLPAP_TJ-0716A03',
 'MLPAP_TJ-0716A04',
 'MLPAP_TJ-0716A05',
 'MLPAP_TJ-0716A06',
 'MLPAP_TJ-0716A07',
 'MLPAP_TJ-0716A08',
 'MLPAP_TJ-0716A09',
 'MLPAP_TJ-0716A10',
 'MLPAP_TJ-0716A11',
 'MLPAP_TJ-0716A12',
 'MLPAP_TJ-0716A13',
 'MLPAP_TJ-0716A14',
 'MLPAP_TJ-0716A15',
 'MLPAP_TJ-0716A16',
 'MLPAP_TJ-0716A17',
 'MLPAP_TJ-0716A18',
 'MLPAP_TJ-0716A19',
 'MLPAP_TJ-0716A20',
 'MLPAP_TJ-0716A21',
 'MLPAP_TJ-0716A22',
 'MLPAP_TJ-0716A23',
 'MLPAP_TJ-0716B01',
 'MLPAP_TJ-0716C01',
 'MLPAP_TJ-0716D01',
 'MLPAP_TJ-0716D02',
 'MLPAP_TJ-0716E01',
 'MLPAP_TJ-0757B.PV',
 'MLPAP_TJ3-1110.PV',
 'MLPAP_TJC-0627.PV',
 'MLPAP_TJC-0757.PV',
 'MLPAP_TJC-0757A.PV',
 'MLPAP_TJC-1721.PV',
 'MLPAP_TJR-0715A1.PV',
 'MLPAP_TJR-0715A2.PV',
 'MLPAP_TJR-0715B1.PV',
 'MLPAP_TJR-0715B2.PV',
 'MLPAP_TJR-0720A1.PV',
 'MLPAP_TJR-0720A2.PV',
 'MLPAP_TJR-0720B1.PV',
 'MLPAP_TJR-0720B2.PV',
 'MLPAP_TJR-0721.PV',
 'MLPAP_TJR-0762A1.PV',
 'MLPAP_TJR-0762A2.PV',
 'MLPAP_TJR-0762B1.PV',
 'MLPAP_TJR-0762B2.PV',
 'MLPAP_TJR-0881.PV',
 'MLPAP_TRC-0610.PV',
 'MLPAP_TRC-0747.PV',
 'MLPAP_TRC-0762.PV',
 'MLPAP_TRC-1734.PV',
 'MLPAP_V225-PHD'}

# convert time

In [16]:
def convert_time(x):
    a,b = str(x).split('*')
    return float(a)*float(b)
df['DATA OF USE'] = [convert_time(i) for i in df['DATA OF USE'].values]
df[['DATA OF USE']].sample(5)

                     DATA OF USE
2016-06-14 20:10:00     0.025238
2019-11-18 12:20:00     0.882549
2017-04-25 17:00:00     0.240901
2019-02-26 12:10:00     0.701037
2016-06-07 18:20:00     0.020391

# replace error value

In [17]:
df = df.replace('[-11059] No Good Data For Calculation',np.nan)
df = df.replace('Scan Off',np.nan)
df = df.replace('Not Connect',np.nan)
df = df.replace('I/O Timeout',np.nan)
df = df.replace('Bad',np.nan)
df = df.replace('#VALUE!',np.nan)
df = df.astype('float32')

# spec fliter

In [18]:
for i in tqdm(set(df.columns)&set(tag.TAG)):
    try:
        lb = float(tag[tag['TAG']==i]['min'].values[0])
        ub = float(tag[tag['TAG']==i]['max'].values[0])
        out = (df[i]<lb)|(df[i]>ub)
        
        # 重點
        df.loc[out,i] = np.nan
    
    except:
        print(i)
df.head()

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=95.0), HTML(value='')))

DATA OF USE

,MLPAP_TJ-0706B02,MLPAP_TJ-0706B03,MLPAP_TJ-0706B04,MLPAP_TJ-0706B05,MLPAP_TJ-0706B06,MLPAP_TJ-0706B07,MLPAP_TJ-0706B08,MLPAP_TJ-0706B09,MLPAP_TJ-0706B10,MLPAP_TJ-0706B11,...,MLPAP_FI-V211.PV(轉換後),MLPAP_PI-0658.PV,MLPAP_TJC-0757.PV,MLPAP_V225-PHD,MLPAP_PI-0771.PV,MLPAP_TRC-0747.PV,MLPAP_TJR-0881.PV,MLPAP_TJ3-1110.PV,MLPAP_FQI-0997.SMH,MLPAP_FR-0755.PV(轉換後)
2016-05-09 00:00:00,400.0,401.957123,400.751862,402.250793,401.148773,401.0,400.050079,403.0,402.0,401.0,...,NaN,NaN,1.635186,0.009,NaN,133.100006,156.434341,26.475903,0.0,NaN
2016-05-09 00:10:00,400.0,401.942719,400.949890,402.249146,401.000000,401.0,400.249786,403.0,402.0,401.0,...,NaN,NaN,1.625011,0.009,NaN,133.100006,156.434296,26.500000,0.0,NaN
2016-05-09 00:20:00,400.0,401.900146,400.899780,402.101257,401.000000,401.0,400.100159,403.0,402.0,401.0,...,NaN,NaN,1.649780,0.009,NaN,133.100006,156.500000,26.700001,0.0,NaN
2016-05-09 00:30:00,400.0,401.949921,400.900208,402.300323,401.000000,401.0,400.144684,403.0,402.0,401.0,...,NaN,NaN,1.635187,0.009,NaN,133.199997,156.434341,26.624229,0.0,NaN
2016-05-09 00:40:00,400.0,402.000000,400.850037,402.176056,401.000000,401.0,400.404999,403.0,402.0,401.0,...,NaN,NaN,1.654259,0.009,NaN,133.100006,156.434341,26.400000,0.0,NaN

# become stable

In [19]:
df = df.rolling(window=36,min_periods=1).median()#主要是平滑

In [20]:
df[['DATA OF USE']].head(40)

                     DATA OF USE
2016-05-09 00:00:00     0.000005
2016-05-09 00:10:00     0.000007
2016-05-09 00:20:00     0.000010
2016-05-09 00:30:00     0.000012
2016-05-09 00:40:00     0.000014
2016-05-09 00:50:00     0.000017
2016-05-09 01:00:00     0.000019
2016-05-09 01:10:00     0.000021
2016-05-09 01:20:00     0.000024
2016-05-09 01:30:00     0.000026
2016-05-09 01:40:00     0.000029
2016-05-09 01:50:00     0.000031
2016-05-09 02:00:00     0.000033
2016-05-09 02:10:00     0.000036
2016-05-09 02:20:00     0.000038
2016-05-09 02:30:00     0.000040
2016-05-09 02:40:00     0.000043
2016-05-09 02:50:00     0.000045
2016-05-09 03:00:00     0.000048
2016-05-09 03:10:00     0.000050
2016-05-09 03:20:00     0.000052
2016-05-09 03:30:00     0.000055
2016-05-09 03:40:00     0.000057
2016-05-09 03:50:00     0.000059
2016-05-09 04:00:00     0.000062
2016-05-09 04:10:00     0.000064
2016-05-09 04:20:00     0.000067
2016-05-09 04:30:00     0.000069
2016-05-09 04:40:00     0.000071
2016-05-09 04:50:00     0.000074
2016-05-09 05:00:00     0.000076
2016-05-09 05:10:00     0.000078
2016-05-09 05:20:00     0.000081
2016-05-09 05:30:00     0.000083
2016-05-09 05:40:00     0.000086
2016-05-09 05:50:00     0.000088
2016-05-09 06:00:00     0.000093
2016-05-09 06:10:00     0.000098
2016-05-09 06:20:00     0.000102
2016-05-09 06:30:00     0.000107

In [21]:
stream_list

['MLPAP_FR-0755PV(轉換後)', 'MLPAP_FR-0791.PV', 'MLPAP_FI-V211.PV(轉換後)']

In [22]:
df[stream_list].isnull().sum().sort_values(ascending=False)

MLPAP_FI-V211.PV(轉換後)    117572
MLPAP_FR-0791.PV          49632
MLPAP_FR-0755PV(轉換後)       2452
dtype: int64

In [23]:
tag.tail(10)

,item,TAG,chinese,character,unit,category,period,min,max,推測顯著性(依製程經驗)
88,89.0,MLPAP_TJC-0757.PV,反應器A/B側鹽浴溫度差,溫度,℃,可控制因子,1分鐘2筆,-3,3,***
89,90.0,MLPAP_PI-0771.PV,E220出口壓力,壓力,mbar,不可控制因子,1分鐘2筆,0,200,***
90,91.0,MLPAP_TRC-0747.PV,E220出口溫度,溫度,℃,可控制因子,1分鐘2筆,100,200,***
91,92.0,MLPAP_TJ-0881.PV,液態冷凝器出口溫度,溫度,℃,可控制因子,1分鐘2筆,130,190,***
92,93.0,MLPAP_TJ3-1110.PV,環境溫度,溫度,℃,不可控制因子,1分鐘2筆,20,40,***
93,94.0,MLPAP_FQI-0997.SMH,粗PA累積出料量,流量,T,可控制因子,1分鐘2筆,0,300000,***
94,NaN,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,NaN,品質模型使用,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,96.0,MLPAP_V225-PHD,粗PA儲槽PHD,組成,%,不可控制因子,1天1筆,0,0.1,***
97,5.0,MLPAP_TJ-0757B.PV,反應槽鹽浴溫度,溫度,℃,可控制因子,1分鐘2筆,345,365,****

# save

In [24]:
df.to_csv('C:/Users/bigje/Desktop/AI中心/yo-jupyter/R11程式/train_cleaned.csv' ,encoding='utf_8_sig')
tag.to_csv('C:/Users/bigje/Desktop/AI中心/yo-jupyter/R11程式/tag_cleaned.csv',encoding='utf_8_sig')
print(time.ctime())

Fri Oct 23 11:54:57 2020

# -----用rpy2以R語言的匯入方式寫入data-----

In [65]:
import rpy2.robjects as robjects

In [62]:
# #coding=utf8
# import sys
# import importlib
# importlib.reload(sys)

In [63]:
%%R
#匯入train_cleaned.csv from ETL-----
r1=read.csv("C:/Users/bigje/Desktop/AI中心/yo-jupyter/R11程式/train_cleaned(R).csv", encoding='latin1')
#r1=read.csv("C:/Users/bigje/Desktop/AI中心/yo-jupyter/R11程式/train_cleaned.csv", encoding='unicode_escape')
names(r1)[1]="ts"